name: Generate content

on:
  repository_dispatch:
    types:
      - generate_content

jobs:
  automate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python tools/generate_content.py
        env:
          CODA_API_KEY: ${{ secrets.CODA_API_KEY }}

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'content/ static/tags.css'
          default_author: github_actions
          message: 'Generated content'
          new_branch: content
          push: 'origin content --set-upstream --force'